services:
  manager:
    image: golang:1.26
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
    working_dir: /app
    command: go run cmd/manager/main.go
    ports:
      - "50051:50051"

  spawner:
    image: golang:1.26
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
    working_dir: /app
    command: go run cmd/spawner/main.go
    environment:
      - MANAGER_ADDR=manager:50051
    depends_on:
      - manager

volumes:
  go-cache: