services:
  manager:
    image: golang:1.26
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
    working_dir: /app
    command: go run cmd/manager/main.go
    ports:
      - "50051:50051"

  agent-1:
    image: golang:1.26
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
    working_dir: /app
    command: go run cmd/agent/main.go
    environment:
      - MANAGER_ADDR=manager:50051
      - VEHICLE_ID=CAR_001
      - START_SPEED=50
      - START_DISTANCE=500  # ETA: 10s
      - ORIGIN_LANE=NORTH   # Da Nord
      - DIRECTION=STRAIGHT  # Va dritto
    depends_on:
      - manager

  agent-2:
    image: golang:1.26
    volumes:
      - .:/app
      - go-cache:/go/pkg/mod
    working_dir: /app
    command: go run cmd/agent/main.go
    environment:
      - MANAGER_ADDR=manager:50051
      - VEHICLE_ID=CAR_002
      - START_SPEED=40
      - START_DISTANCE=400  # ETA: 10s (Identico a CAR_001)
      - ORIGIN_LANE=SOUTH   # Da Sud
      - DIRECTION=STRAIGHT  # Va dritto
    depends_on:
      - manager

volumes:
  go-cache: