// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/intersection.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lane int32

const (
	Lane_LANE_UNKNOWN Lane = 0 // Default di sicurezza in gRPC
	Lane_LANE_NORTH   Lane = 1
	Lane_LANE_SOUTH   Lane = 2
	Lane_LANE_EAST    Lane = 3
	Lane_LANE_WEST    Lane = 4
)

// Enum value maps for Lane.
var (
	Lane_name = map[int32]string{
		0: "LANE_UNKNOWN",
		1: "LANE_NORTH",
		2: "LANE_SOUTH",
		3: "LANE_EAST",
		4: "LANE_WEST",
	}
	Lane_value = map[string]int32{
		"LANE_UNKNOWN": 0,
		"LANE_NORTH":   1,
		"LANE_SOUTH":   2,
		"LANE_EAST":    3,
		"LANE_WEST":    4,
	}
)

func (x Lane) Enum() *Lane {
	p := new(Lane)
	*p = x
	return p
}

func (x Lane) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Lane) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_intersection_proto_enumTypes[0].Descriptor()
}

func (Lane) Type() protoreflect.EnumType {
	return &file_proto_intersection_proto_enumTypes[0]
}

func (x Lane) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Lane.Descriptor instead.
func (Lane) EnumDescriptor() ([]byte, []int) {
	return file_proto_intersection_proto_rawDescGZIP(), []int{0}
}

type Direction int32

const (
	Direction_DIR_UNKNOWN  Direction = 0
	Direction_DIR_STRAIGHT Direction = 1
	Direction_DIR_LEFT     Direction = 2
	Direction_DIR_RIGHT    Direction = 3
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIR_UNKNOWN",
		1: "DIR_STRAIGHT",
		2: "DIR_LEFT",
		3: "DIR_RIGHT",
	}
	Direction_value = map[string]int32{
		"DIR_UNKNOWN":  0,
		"DIR_STRAIGHT": 1,
		"DIR_LEFT":     2,
		"DIR_RIGHT":    3,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_intersection_proto_enumTypes[1].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_proto_intersection_proto_enumTypes[1]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_proto_intersection_proto_rawDescGZIP(), []int{1}
}

type CommandStatus int32

const (
	CommandStatus_STATUS_UNKNOW       CommandStatus = 0 // Default state to avoid accidental commands
	CommandStatus_STATUS_ACK_LOCK     CommandStatus = 1 // Access allowed, intersection blocked for the vehicle
	CommandStatus_STATUS_REJECT       CommandStatus = 2 // Access denied, vehicle must stop or recalculate
	CommandStatus_STATUS_ADJUST_SPEED CommandStatus = 3 // Request to change speed to optimize flow
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "STATUS_UNKNOW",
		1: "STATUS_ACK_LOCK",
		2: "STATUS_REJECT",
		3: "STATUS_ADJUST_SPEED",
	}
	CommandStatus_value = map[string]int32{
		"STATUS_UNKNOW":       0,
		"STATUS_ACK_LOCK":     1,
		"STATUS_REJECT":       2,
		"STATUS_ADJUST_SPEED": 3,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_intersection_proto_enumTypes[2].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_proto_intersection_proto_enumTypes[2]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_intersection_proto_rawDescGZIP(), []int{2}
}

type VehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Speed         float64                `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"` // m/s
	Eta           float64                `protobuf:"fixed64,3,opt,name=eta,proto3" json:"eta,omitempty"`     //Seconds estimate to arrive
	OriginLane    Lane                   `protobuf:"varint,4,opt,name=origin_lane,json=originLane,proto3,enum=intersection.Lane" json:"origin_lane,omitempty"`
	Direction     Direction              `protobuf:"varint,5,opt,name=direction,proto3,enum=intersection.Direction" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleRequest) Reset() {
	*x = VehicleRequest{}
	mi := &file_proto_intersection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleRequest) ProtoMessage() {}

func (x *VehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_intersection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleRequest.ProtoReflect.Descriptor instead.
func (*VehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_intersection_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *VehicleRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *VehicleRequest) GetEta() float64 {
	if x != nil {
		return x.Eta
	}
	return 0
}

func (x *VehicleRequest) GetOriginLane() Lane {
	if x != nil {
		return x.OriginLane
	}
	return Lane_LANE_UNKNOWN
}

func (x *VehicleRequest) GetDirection() Direction {
	if x != nil {
		return x.Direction
	}
	return Direction_DIR_UNKNOWN
}

type ManagerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Status        CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=intersection.CommandStatus" json:"status,omitempty"`
	TargetEta     float64                `protobuf:"fixed64,3,opt,name=target_eta,json=targetEta,proto3" json:"target_eta,omitempty"` //L'istante di tempo suggerito dal Manager
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerResponse) Reset() {
	*x = ManagerResponse{}
	mi := &file_proto_intersection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerResponse) ProtoMessage() {}

func (x *ManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_intersection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerResponse.ProtoReflect.Descriptor instead.
func (*ManagerResponse) Descriptor() ([]byte, []int) {
	return file_proto_intersection_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerResponse) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *ManagerResponse) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_STATUS_UNKNOW
}

func (x *ManagerResponse) GetTargetEta() float64 {
	if x != nil {
		return x.TargetEta
	}
	return 0
}

var File_proto_intersection_proto protoreflect.FileDescriptor

const file_proto_intersection_proto_rawDesc = "" +
	"\n" +
	"\x18proto/intersection.proto\x12\fintersection\"\xc3\x01\n" +
	"\x0eVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\x01R\x05speed\x12\x10\n" +
	"\x03eta\x18\x03 \x01(\x01R\x03eta\x123\n" +
	"\vorigin_lane\x18\x04 \x01(\x0e2\x12.intersection.LaneR\n" +
	"originLane\x125\n" +
	"\tdirection\x18\x05 \x01(\x0e2\x17.intersection.DirectionR\tdirection\"\x84\x01\n" +
	"\x0fManagerResponse\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.intersection.CommandStatusR\x06status\x12\x1d\n" +
	"\n" +
	"target_eta\x18\x03 \x01(\x01R\ttargetEta*V\n" +
	"\x04Lane\x12\x10\n" +
	"\fLANE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"LANE_NORTH\x10\x01\x12\x0e\n" +
	"\n" +
	"LANE_SOUTH\x10\x02\x12\r\n" +
	"\tLANE_EAST\x10\x03\x12\r\n" +
	"\tLANE_WEST\x10\x04*K\n" +
	"\tDirection\x12\x0f\n" +
	"\vDIR_UNKNOWN\x10\x00\x12\x10\n" +
	"\fDIR_STRAIGHT\x10\x01\x12\f\n" +
	"\bDIR_LEFT\x10\x02\x12\r\n" +
	"\tDIR_RIGHT\x10\x03*c\n" +
	"\rCommandStatus\x12\x11\n" +
	"\rSTATUS_UNKNOW\x10\x00\x12\x13\n" +
	"\x0fSTATUS_ACK_LOCK\x10\x01\x12\x11\n" +
	"\rSTATUS_REJECT\x10\x02\x12\x17\n" +
	"\x13STATUS_ADJUST_SPEED\x10\x032c\n" +
	"\x13IntersectionService\x12L\n" +
	"\tNegotiate\x12\x1c.intersection.VehicleRequest\x1a\x1d.intersection.ManagerResponse(\x010\x01B=Z;github.com/Vittorio17/Autonomous-Intersection-Manager/protob\x06proto3"

var (
	file_proto_intersection_proto_rawDescOnce sync.Once
	file_proto_intersection_proto_rawDescData []byte
)

func file_proto_intersection_proto_rawDescGZIP() []byte {
	file_proto_intersection_proto_rawDescOnce.Do(func() {
		file_proto_intersection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_intersection_proto_rawDesc), len(file_proto_intersection_proto_rawDesc)))
	})
	return file_proto_intersection_proto_rawDescData
}

var file_proto_intersection_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_intersection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_intersection_proto_goTypes = []any{
	(Lane)(0),               // 0: intersection.Lane
	(Direction)(0),          // 1: intersection.Direction
	(CommandStatus)(0),      // 2: intersection.CommandStatus
	(*VehicleRequest)(nil),  // 3: intersection.VehicleRequest
	(*ManagerResponse)(nil), // 4: intersection.ManagerResponse
}
var file_proto_intersection_proto_depIdxs = []int32{
	0, // 0: intersection.VehicleRequest.origin_lane:type_name -> intersection.Lane
	1, // 1: intersection.VehicleRequest.direction:type_name -> intersection.Direction
	2, // 2: intersection.ManagerResponse.status:type_name -> intersection.CommandStatus
	3, // 3: intersection.IntersectionService.Negotiate:input_type -> intersection.VehicleRequest
	4, // 4: intersection.IntersectionService.Negotiate:output_type -> intersection.ManagerResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_intersection_proto_init() }
func file_proto_intersection_proto_init() {
	if File_proto_intersection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_intersection_proto_rawDesc), len(file_proto_intersection_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_intersection_proto_goTypes,
		DependencyIndexes: file_proto_intersection_proto_depIdxs,
		EnumInfos:         file_proto_intersection_proto_enumTypes,
		MessageInfos:      file_proto_intersection_proto_msgTypes,
	}.Build()
	File_proto_intersection_proto = out.File
	file_proto_intersection_proto_goTypes = nil
	file_proto_intersection_proto_depIdxs = nil
}
