// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/intersection.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IntersectionService_Negotiate_FullMethodName = "/intersection.IntersectionService/Negotiate"
)

// IntersectionServiceClient is the client API for IntersectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IntersectionServiceClient interface {
	// Bidirectional stream with an open channel
	Negotiate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VehicleRequest, ManagerResponse], error)
}

type intersectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIntersectionServiceClient(cc grpc.ClientConnInterface) IntersectionServiceClient {
	return &intersectionServiceClient{cc}
}

func (c *intersectionServiceClient) Negotiate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[VehicleRequest, ManagerResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &IntersectionService_ServiceDesc.Streams[0], IntersectionService_Negotiate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VehicleRequest, ManagerResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntersectionService_NegotiateClient = grpc.BidiStreamingClient[VehicleRequest, ManagerResponse]

// IntersectionServiceServer is the server API for IntersectionService service.
// All implementations must embed UnimplementedIntersectionServiceServer
// for forward compatibility.
type IntersectionServiceServer interface {
	// Bidirectional stream with an open channel
	Negotiate(grpc.BidiStreamingServer[VehicleRequest, ManagerResponse]) error
	mustEmbedUnimplementedIntersectionServiceServer()
}

// UnimplementedIntersectionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIntersectionServiceServer struct{}

func (UnimplementedIntersectionServiceServer) Negotiate(grpc.BidiStreamingServer[VehicleRequest, ManagerResponse]) error {
	return status.Error(codes.Unimplemented, "method Negotiate not implemented")
}
func (UnimplementedIntersectionServiceServer) mustEmbedUnimplementedIntersectionServiceServer() {}
func (UnimplementedIntersectionServiceServer) testEmbeddedByValue()                             {}

// UnsafeIntersectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IntersectionServiceServer will
// result in compilation errors.
type UnsafeIntersectionServiceServer interface {
	mustEmbedUnimplementedIntersectionServiceServer()
}

func RegisterIntersectionServiceServer(s grpc.ServiceRegistrar, srv IntersectionServiceServer) {
	// If the following call panics, it indicates UnimplementedIntersectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IntersectionService_ServiceDesc, srv)
}

func _IntersectionService_Negotiate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(IntersectionServiceServer).Negotiate(&grpc.GenericServerStream[VehicleRequest, ManagerResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type IntersectionService_NegotiateServer = grpc.BidiStreamingServer[VehicleRequest, ManagerResponse]

// IntersectionService_ServiceDesc is the grpc.ServiceDesc for IntersectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IntersectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "intersection.IntersectionService",
	HandlerType: (*IntersectionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Negotiate",
			Handler:       _IntersectionService_Negotiate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/intersection.proto",
}
