// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/intersection.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CommandStatus int32

const (
	CommandStatus_STATUS_UNKNOW       CommandStatus = 0 // Default state to avoid accidental commands
	CommandStatus_STATUS_ACK_LOCK     CommandStatus = 1 // Access allowed, intersection blocked for the vehicle
	CommandStatus_STATUS_REJECT       CommandStatus = 2 // Access denied, vehicle must stop or recalculate
	CommandStatus_STATUS_ADJUST_SPEED CommandStatus = 3 // Request to change speed to optimize flow
)

// Enum value maps for CommandStatus.
var (
	CommandStatus_name = map[int32]string{
		0: "STATUS_UNKNOW",
		1: "STATUS_ACK_LOCK",
		2: "STATUS_REJECT",
		3: "STATUS_ADJUST_SPEED",
	}
	CommandStatus_value = map[string]int32{
		"STATUS_UNKNOW":       0,
		"STATUS_ACK_LOCK":     1,
		"STATUS_REJECT":       2,
		"STATUS_ADJUST_SPEED": 3,
	}
)

func (x CommandStatus) Enum() *CommandStatus {
	p := new(CommandStatus)
	*p = x
	return p
}

func (x CommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_intersection_proto_enumTypes[0].Descriptor()
}

func (CommandStatus) Type() protoreflect.EnumType {
	return &file_proto_intersection_proto_enumTypes[0]
}

func (x CommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandStatus.Descriptor instead.
func (CommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_intersection_proto_rawDescGZIP(), []int{0}
}

type VehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Speed         float64                `protobuf:"fixed64,2,opt,name=speed,proto3" json:"speed,omitempty"` // m/s
	Eta           float64                `protobuf:"fixed64,3,opt,name=eta,proto3" json:"eta,omitempty"`     //Seconds estimate to arrive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleRequest) Reset() {
	*x = VehicleRequest{}
	mi := &file_proto_intersection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleRequest) ProtoMessage() {}

func (x *VehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_intersection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleRequest.ProtoReflect.Descriptor instead.
func (*VehicleRequest) Descriptor() ([]byte, []int) {
	return file_proto_intersection_proto_rawDescGZIP(), []int{0}
}

func (x *VehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *VehicleRequest) GetSpeed() float64 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *VehicleRequest) GetEta() float64 {
	if x != nil {
		return x.Eta
	}
	return 0
}

type ManagerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Status        CommandStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=intersection.CommandStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManagerResponse) Reset() {
	*x = ManagerResponse{}
	mi := &file_proto_intersection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManagerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerResponse) ProtoMessage() {}

func (x *ManagerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_intersection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerResponse.ProtoReflect.Descriptor instead.
func (*ManagerResponse) Descriptor() ([]byte, []int) {
	return file_proto_intersection_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerResponse) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *ManagerResponse) GetStatus() CommandStatus {
	if x != nil {
		return x.Status
	}
	return CommandStatus_STATUS_UNKNOW
}

var File_proto_intersection_proto protoreflect.FileDescriptor

const file_proto_intersection_proto_rawDesc = "" +
	"\n" +
	"\x18proto/intersection.proto\x12\fintersection\"W\n" +
	"\x0eVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12\x14\n" +
	"\x05speed\x18\x02 \x01(\x01R\x05speed\x12\x10\n" +
	"\x03eta\x18\x03 \x01(\x01R\x03eta\"e\n" +
	"\x0fManagerResponse\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x123\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1b.intersection.CommandStatusR\x06status*c\n" +
	"\rCommandStatus\x12\x11\n" +
	"\rSTATUS_UNKNOW\x10\x00\x12\x13\n" +
	"\x0fSTATUS_ACK_LOCK\x10\x01\x12\x11\n" +
	"\rSTATUS_REJECT\x10\x02\x12\x17\n" +
	"\x13STATUS_ADJUST_SPEED\x10\x032c\n" +
	"\x13IntersectionService\x12L\n" +
	"\tNegotiate\x12\x1c.intersection.VehicleRequest\x1a\x1d.intersection.ManagerResponse(\x010\x01B=Z;github.com/Vittorio17/Autonomous-Intersection-Manager/protob\x06proto3"

var (
	file_proto_intersection_proto_rawDescOnce sync.Once
	file_proto_intersection_proto_rawDescData []byte
)

func file_proto_intersection_proto_rawDescGZIP() []byte {
	file_proto_intersection_proto_rawDescOnce.Do(func() {
		file_proto_intersection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_intersection_proto_rawDesc), len(file_proto_intersection_proto_rawDesc)))
	})
	return file_proto_intersection_proto_rawDescData
}

var file_proto_intersection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_intersection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_intersection_proto_goTypes = []any{
	(CommandStatus)(0),      // 0: intersection.CommandStatus
	(*VehicleRequest)(nil),  // 1: intersection.VehicleRequest
	(*ManagerResponse)(nil), // 2: intersection.ManagerResponse
}
var file_proto_intersection_proto_depIdxs = []int32{
	0, // 0: intersection.ManagerResponse.status:type_name -> intersection.CommandStatus
	1, // 1: intersection.IntersectionService.Negotiate:input_type -> intersection.VehicleRequest
	2, // 2: intersection.IntersectionService.Negotiate:output_type -> intersection.ManagerResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_intersection_proto_init() }
func file_proto_intersection_proto_init() {
	if File_proto_intersection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_intersection_proto_rawDesc), len(file_proto_intersection_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_intersection_proto_goTypes,
		DependencyIndexes: file_proto_intersection_proto_depIdxs,
		EnumInfos:         file_proto_intersection_proto_enumTypes,
		MessageInfos:      file_proto_intersection_proto_msgTypes,
	}.Build()
	File_proto_intersection_proto = out.File
	file_proto_intersection_proto_goTypes = nil
	file_proto_intersection_proto_depIdxs = nil
}
