syntax = "proto3";

package intersection;

option go_package = "github.com/Vittorio17/Autonomous-Intersection-Manager/proto";

enum Lane {
  LANE_UNKNOWN = 0; // Default di sicurezza in gRPC
  LANE_NORTH = 1;
  LANE_SOUTH = 2;
  LANE_EAST = 3;
  LANE_WEST = 4;
}

enum Direction {
  DIR_UNKNOWN = 0;
  DIR_STRAIGHT = 1;
  DIR_LEFT = 2;
  DIR_RIGHT = 3;
}

service IntersectionService{
    //Bidirectional stream with an open channel
    rpc Negotiate(stream VehicleRequest) returns (stream ManagerResponse);
}

message VehicleRequest{
    string vehicle_id = 1;
    double speed = 2; // m/s
    double eta = 3; //Seconds estimate to arrive
    Lane origin_lane = 4;
    Direction direction = 5;
}

enum CommandStatus{
    STATUS_UNKNOW = 0; // Default state to avoid accidental commands
    STATUS_ACK_LOCK = 1; // Access allowed, intersection blocked for the vehicle
    STATUS_REJECT = 2; // Access denied, vehicle must stop or recalculate
    STATUS_ADJUST_SPEED = 3; // Request to change speed to optimize flow
}

message ManagerResponse{
    string vehicle_id = 1;
    CommandStatus status = 2;
}